# Generated by Django 3.1.7 on 2021-05-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210509_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='PhNumber',
            field=models.IntegerField(),
        ),
    ]
