# Generated by Django 3.1.7 on 2021-05-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210509_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock',
            name='Email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
