# Generated by Django 3.1.7 on 2021-05-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210509_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Stock',
            new_name='Accounts',
        ),
    ]
