# Generated by Django 3.1.7 on 2021-05-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210510_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accs',
            fields=[
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('PhNumber', models.IntegerField()),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
