# Generated by Django 3.1.7 on 2021-05-18 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0013_auto_20210517_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Bod', models.DateField(max_length=8)),
                ('PhNumber', models.IntegerField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Marital', models.CharField(choices=[('S', 'Single'), ('M', 'Married')], max_length=1)),
                ('Pan', models.CharField(max_length=10)),
                ('AadharNumber', models.IntegerField(max_length=12)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Accs',
        ),
    ]
