# Generated by Django 3.1.7 on 2021-05-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20210518_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dash',
            name='stocks',
            field=models.CharField(default='you dont have stocks', max_length=100),
        ),
    ]
