# Generated by Django 3.1.7 on 2021-05-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20210518_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dash',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
