# Generated by Django 3.1.7 on 2021-05-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20210518_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='dash',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
