# Generated by Django 3.1.7 on 2021-05-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_dash_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dash',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
